[project]
name = "lalamove-sdk"
version = "0.1.0"
description = "Unofficial sdk for lalamove delivery api integration."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "inflection>=0.5.1",
    "pydantic>=2.11.5",
]
